name: Workflow
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    continue-on-error: False
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Node.js
        uses: actions/setup-node@v4

      # Install modules
      - name: Install modules
        run: yarn install

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      # Run linters
      - name: Run ESLint
        run: ./node_modules/.bin/eslint . --ext .js,.jsx,.ts,.tsx
      - name: Run solhint
        run: ./node_modules/.bin/solhint contracts/p1/*.sol contracts/test/*.sol

      # Compile the code and run tests and deploy script(s)
      - name: Compile the code
        run: ./node_modules/.bin/hardhat compile
      - name: Run tests
        run: ./node_modules/.bin/hardhat test

      # Run hardhat coverage and upload codecov report
      - name: Solidity coverage summary
        run: ./node_modules/.bin/hardhat coverage

      # Compile the code and run foundry tests
      - name: Run foundry tests
        run: forge test --hh -vvv
